import { contextBridge, ipcRenderer } from 'electron'
import { electronAPI } from '@electron-toolkit/preload'

const api = {
  auth: {
    localSignIn:         (email: string, password: string) => ipcRenderer.invoke('auth:localSignIn', email, password),
    changeLocalPassword: (current: string, next: string)   => ipcRenderer.invoke('auth:changeLocalPassword', current, next),
    syncAllToSupabase:   ()                                => ipcRenderer.invoke('auth:syncAllToSupabase'),
  },
  settings: {
    get:    (key: string)              => ipcRenderer.invoke('settings:get', key),
    set:    (key: string, val: string) => ipcRenderer.invoke('settings:set', key, val),
    delete: (key: string)              => ipcRenderer.invoke('settings:delete', key),
    getAll: ()                         => ipcRenderer.invoke('settings:getAll'),
  },
  projects: {
    getAll:  ()                            => ipcRenderer.invoke('projects:getAll'),
    upsert:  (p: Record<string, unknown>) => ipcRenderer.invoke('projects:upsert', p),
  },
  tasks: {
    getByProject: (projectId: string) => ipcRenderer.invoke('tasks:getByProject', projectId),
  },
  comments: {
    get:    (taskId: string)    => ipcRenderer.invoke('comments:get', taskId),
    add:    (c: { task_id: string; author_id: string; author_name: string; content: string; task_title?: string; assignee_ids?: string[] }) => ipcRenderer.invoke('comments:add', c),
    delete: (id: string, deletedById?: string, deletedByName?: string) => ipcRenderer.invoke('comments:delete', id, deletedById, deletedByName),
    update: (id: string, content: string) => ipcRenderer.invoke('comments:update', id, content),
  },
  activity: {
    get:     (taskId: string) => ipcRenderer.invoke('activity:get', taskId),
    add:     (e: { task_id: string; actor_name: string; action: string }) => ipcRenderer.invoke('activity:add', e),
    getFeed: (actorId?: string) => ipcRenderer.invoke('activity:getFeed', actorId),
  },
  team: {
    list:            (includeAdmin?: boolean)                                              => ipcRenderer.invoke('team:list', includeAdmin),
    invite:          (p: { email: string; full_name: string; role?: string })             => ipcRenderer.invoke('team:invite', p),
    remove:          (id: string)                                                          => ipcRenderer.invoke('team:remove', id),
    edit:            (p: { id: string; full_name?: string; email?: string; role?: string }) => ipcRenderer.invoke('team:edit', p),
    heartbeat:       (userId: string)                                                      => ipcRenderer.invoke('team:heartbeat', userId),
    changePassword:  (userId: string, cur: string, next: string)                          => ipcRenderer.invoke('team:changePassword', userId, cur, next),
    setInitialPassword: (userId: string, next: string)                                     => ipcRenderer.invoke('team:setInitialPassword', userId, next),
    getLoginCode:    (email: string)                                                       => ipcRenderer.invoke('team:getLoginCode', email),
    markActive:      (id: string)                                                          => ipcRenderer.invoke('team:markActive', id),
    markApiKeySet:   (userId: string)                                                      => ipcRenderer.invoke('team:markApiKeySet', userId),
    savePreferences: (userId: string, prefs: Record<string, unknown>)                     => ipcRenderer.invoke('team:savePreferences', userId, prefs),
  },
  drive: {
    connect:        ()              => ipcRenderer.invoke('drive:connect'),
    getStatus:      ()              => ipcRenderer.invoke('drive:getStatus'),
    getAuthUrl:     ()              => ipcRenderer.invoke('drive:getAuthUrl'),
    exchangeCode:   (code: string)  => ipcRenderer.invoke('drive:exchangeCode', code),
    syncNow:        ()              => ipcRenderer.invoke('drive:syncNow'),
    disconnect:     ()              => ipcRenderer.invoke('drive:disconnect'),
    isConnected:    ()              => ipcRenderer.invoke('drive:isConnected'),
    reinit:         ()              => ipcRenderer.invoke('drive:reinit'),
    listFolder:     (folderPath: string) => ipcRenderer.invoke('drive:listFolder', folderPath),
    onStatusChange: (cb: (s: string) => void) => ipcRenderer.on('drive:status', (_e, s) => cb(s)),
  },
  areas: {
    list:   ()                                          => ipcRenderer.invoke('areas:list'),
    create: (name: string, color: string)              => ipcRenderer.invoke('areas:create', name, color),
    update: (id: string, name: string, color: string)  => ipcRenderer.invoke('areas:update', id, name, color),
    delete: (id: string)                               => ipcRenderer.invoke('areas:delete', id),
  },
  app: {
    getVersion: () => ipcRenderer.invoke('app:getVersion'),
    setActingUser: (userId: string | null) => ipcRenderer.invoke('app:setActingUser', userId),
  },
  claude: {
    sendMessage: (params: { messages: { role: 'user' | 'assistant'; content: string }[]; taskContext: Record<string, string | null>; userId?: string }) =>
      ipcRenderer.invoke('claude:sendMessage', params),
    onChunk:         (cb: (text: string) => void) => ipcRenderer.on('claude:chunk', (_e, text) => cb(text)),
    onDone:          (cb: () => void)              => ipcRenderer.on('claude:done', () => cb()),
    onError:         (cb: (err: string) => void)   => ipcRenderer.on('claude:error', (_e, err) => cb(err)),
    removeListeners: () => {
      ipcRenderer.removeAllListeners('claude:chunk')
      ipcRenderer.removeAllListeners('claude:done')
      ipcRenderer.removeAllListeners('claude:error')
    },
    saveUserKey:      (userId: string, apiKey: string) => ipcRenderer.invoke('claude:saveUserKey', userId, apiKey),
    removeUserKey:    (userId: string)                 => ipcRenderer.invoke('claude:removeUserKey', userId),
    getUserKeyStatus: (userId: string)                 => ipcRenderer.invoke('claude:getUserKeyStatus', userId),
  },
  labels: {
    list:   ()                                          => ipcRenderer.invoke('labels:list'),
    create: (name: string, color: string)              => ipcRenderer.invoke('labels:create', name, color),
    update: (id: string, name: string, color: string)  => ipcRenderer.invoke('labels:update', id, name, color),
    delete: (id: string)                               => ipcRenderer.invoke('labels:delete', id),
  },
  taskLabels: {
    get: (taskId: string)                => ipcRenderer.invoke('taskLabels:get', taskId),
    set: (taskId: string, ids: string[]) => ipcRenderer.invoke('taskLabels:set', taskId, ids),
  },
  checklists: {
    get:    (taskId: string)                    => ipcRenderer.invoke('checklists:get', taskId),
    create: (taskId: string, title: string)     => ipcRenderer.invoke('checklists:create', taskId, title),
    delete: (checklistId: string)               => ipcRenderer.invoke('checklists:delete', checklistId),
  },
  checklistItems: {
    add:    (checklistId: string, taskId: string, text: string) => ipcRenderer.invoke('checklistItems:add', checklistId, taskId, text),
    toggle: (itemId: string, checked: boolean)                   => ipcRenderer.invoke('checklistItems:toggle', itemId, checked),
    delete: (itemId: string)                                     => ipcRenderer.invoke('checklistItems:delete', itemId),
    update: (itemId: string, text: string)                       => ipcRenderer.invoke('checklistItems:update', itemId, text),
  },
  attachments: {
    get:         (taskId: string)                                              => ipcRenderer.invoke('attachments:get', taskId),
    // addFile: author args removed — main resolves identity from the ambient acting user.
    addFile:     (taskId: string)                                              => ipcRenderer.invoke('attachments:addFile', taskId),
    addUrl:      (taskId: string, name: string, url: string, type: string)    => ipcRenderer.invoke('attachments:addUrl', taskId, name, url, type),
    delete:      (id: string)                                                  => ipcRenderer.invoke('attachments:delete', id),
    open:        (attachmentId: string)                                        => ipcRenderer.invoke('attachments:open', attachmentId),
    seedToCloud: (requestEmail: string)                                        => ipcRenderer.invoke('attachments:seedToCloud', requestEmail),
  },
  notifications: {
    get:         (userId: string)  => ipcRenderer.invoke('notifications:get', userId),
    unreadCount: (userId: string)  => ipcRenderer.invoke('notifications:unreadCount', userId),
    markRead:    (id: string)      => ipcRenderer.invoke('notifications:markRead', id),
    markAllRead: (userId: string)  => ipcRenderer.invoke('notifications:markAllRead', userId),
    create:      (n: { user_id: string; type: string; title: string; body?: string; task_id?: string; task_title?: string; actor_name?: string }) => ipcRenderer.invoke('notifications:create', n),
  },
  chat: {
    getMessages: (limit?: number) => ipcRenderer.invoke('chat:getMessages', limit ?? 100),
    send:        (msg: { author_id: string; author_name: string; content: string }) => ipcRenderer.invoke('chat:send', msg),
    seedToCloud: (requestEmail: string) => ipcRenderer.invoke('chat:seedToCloud', requestEmail),
  },
  permissions: {
    getMine:              ()                                                              => ipcRenderer.invoke('permissions:getMine'),
    getAll:               ()                                                              => ipcRenderer.invoke('permissions:getAll'),
    set:                  (p: { userEmail: string; key: string; on: boolean })           => ipcRenderer.invoke('permissions:set', p),
    onChange:             (cb: () => void)                                               => ipcRenderer.on('permissions:invalidate', () => cb()),
    removeChangeListeners: ()                                                             => ipcRenderer.removeAllListeners('permissions:invalidate'),
  },
  dialog: {
    openFile: () => ipcRenderer.invoke('dialog:openFile'),
  },
  workspace: {
    getColumns:   (boardId?: string, actorId?: string)   => ipcRenderer.invoke('workspace:getColumns', boardId, actorId),
    getTasks:     (actorId?: string)                      => ipcRenderer.invoke('workspace:getTasks', actorId),
    createTask:   (t: Record<string, unknown>)            => ipcRenderer.invoke('workspace:createTask', t),
    updateTask:   (id: string, p: Record<string, unknown>) => ipcRenderer.invoke('workspace:updateTask', id, p),
    deleteTask:   (id: string, deletedById?: string, deletedByName?: string) => ipcRenderer.invoke('workspace:deleteTask', id, deletedById, deletedByName),
    archiveTask:      (id: string) => ipcRenderer.invoke('workspace:archiveTask', id),
    getArchivedTasks: (actorId?: string) => ipcRenderer.invoke('workspace:getArchivedTasks', actorId),
    restoreTask:      (id: string) => ipcRenderer.invoke('workspace:restoreTask', id),
    markForDeletion:              (id: string)      => ipcRenderer.invoke('workspace:markForDeletion', id),
    adminMarkForDeletion:         (id: string)      => ipcRenderer.invoke('workspace:adminMarkForDeletion', id),
    undeleteTask:                 (id: string)      => ipcRenderer.invoke('workspace:undeleteTask', id),
    markCompleteNow:              (id: string)      => ipcRenderer.invoke('workspace:markCompleteNow', id),
    getCompletedTasks:            (actorId?: string) => ipcRenderer.invoke('workspace:getCompletedTasks', actorId),
    getMarkedForDeletionTasks:    (actorId?: string) => ipcRenderer.invoke('workspace:getMarkedForDeletionTasks', actorId),
    addColumn:    (c: Record<string, unknown>)            => ipcRenderer.invoke('workspace:addColumn', c),
    deleteColumn:    (id: string)                            => ipcRenderer.invoke('workspace:deleteColumn', id),
    updateColumn:    (id: string, p: Record<string, unknown>) => ipcRenderer.invoke('workspace:updateColumn', id, p),
    reorderColumns:  (ids: string[])                         => ipcRenderer.invoke('workspace:reorderColumns', ids),
    // Realtime invalidate push from main (reuses the existing event-bridge pattern).
    onRemoteChange:      (cb: (d: { boardId: string | null; scope: 'list' | 'board' }) => void) =>
      ipcRenderer.on('workspace:remoteChange', (_e, d) => cb(d)),
    removeRemoteChangeListeners: () => ipcRenderer.removeAllListeners('workspace:remoteChange'),
  },
  clients: {
    list:          ()                                         => ipcRenderer.invoke('clients:list'),
    get:           (id: string)                              => ipcRenderer.invoke('clients:get', id),
    create:        (data: Record<string, unknown>)           => ipcRenderer.invoke('clients:create', data),
    update:        (id: string, data: Record<string, unknown>) => ipcRenderer.invoke('clients:update', id, data),
    delete:        (id: string)                              => ipcRenderer.invoke('clients:delete', id),
    addContact:    (clientId: string, c: Record<string, unknown>) => ipcRenderer.invoke('clients:addContact', clientId, c),
    deleteContact: (contactId: string)                       => ipcRenderer.invoke('clients:deleteContact', contactId),
    seedToCloud:  (requestEmail: string)                     => ipcRenderer.invoke('clients:seedToCloud', requestEmail),
  },
  templates: {
    list:   (boardId?: string)                              => ipcRenderer.invoke('templates:list', boardId),
    create: (data: Record<string, unknown>)                 => ipcRenderer.invoke('templates:create', data),
    update: (id: string, data: Record<string, unknown>)    => ipcRenderer.invoke('templates:update', id, data),
    delete: (id: string)                                    => ipcRenderer.invoke('templates:delete', id),
  },
  contacts: {
    list:              ()                                              => ipcRenderer.invoke('contacts:list'),
    listTrash:         ()                                              => ipcRenderer.invoke('contacts:listTrash'),
    get:               (id: string)                                   => ipcRenderer.invoke('contacts:get', id),
    create:            (data: Record<string, unknown>)                => ipcRenderer.invoke('contacts:create', data),
    update:            (id: string, data: Record<string, unknown>)    => ipcRenderer.invoke('contacts:update', id, data),
    softDelete:        (id: string, deletedById?: string)             => ipcRenderer.invoke('contacts:softDelete', id, deletedById),
    restore:           (id: string)                                   => ipcRenderer.invoke('contacts:restore', id),
    permanentDelete:   (id: string, requestEmail: string)             => ipcRenderer.invoke('contacts:permanentDelete', id, requestEmail),
    addInteraction:    (data: Record<string, unknown>)                => ipcRenderer.invoke('contacts:addInteraction', data),
    updateInteraction: (id: string, data: Record<string, unknown>)    => ipcRenderer.invoke('contacts:updateInteraction', id, data),
    deleteInteraction: (id: string)                                   => ipcRenderer.invoke('contacts:deleteInteraction', id),
    linkTask:          (contactId: string, taskId: string)            => ipcRenderer.invoke('contacts:linkTask', contactId, taskId),
    unlinkTask:        (contactId: string, taskId: string)            => ipcRenderer.invoke('contacts:unlinkTask', contactId, taskId),
    onRemoteChange:              (cb: (d: { boardId: string | null; scope: 'list' | 'board' }) => void) =>
      ipcRenderer.on('contacts:remoteChange', (_e, d) => cb(d)),
    removeRemoteChangeListeners: () => ipcRenderer.removeAllListeners('contacts:remoteChange'),
  },
  boards: {
    list:         (includeArchived?: boolean, actorId?: string) => ipcRenderer.invoke('boards:list', includeArchived, actorId),
    listArchived: (actorId?: string)                   => ipcRenderer.invoke('boards:listArchived', actorId),
    create:       (name: string, boardType?: string, boardConfig?: string | null) => ipcRenderer.invoke('boards:create', name, boardType, boardConfig),
    rename:       (id: string, name: string)           => ipcRenderer.invoke('boards:rename', id, name),
    updateConfig: (id: string, config: string | null)  => ipcRenderer.invoke('boards:updateConfig', id, config),
    archive:            (id: string, archivedBy: string)     => ipcRenderer.invoke('boards:archive', id, archivedBy),
    restore:            (id: string)                         => ipcRenderer.invoke('boards:restore', id),
    delete:             (id: string, deletedById?: string, deletedByName?: string) => ipcRenderer.invoke('boards:delete', id, deletedById, deletedByName),
    listTrashed:        ()                                   => ipcRenderer.invoke('boards:listTrashed'),
    permanentlyDelete:  (id: string)                         => ipcRenderer.invoke('boards:permanentlyDelete', id),
    undelete:           (id: string)                         => ipcRenderer.invoke('boards:undelete', id),
    duplicate:          (id: string, newName: string)        => ipcRenderer.invoke('boards:duplicate', id, newName),
    taskCount:    (id: string)                         => ipcRenderer.invoke('boards:taskCount', id),
    getTasks:     (boardId: string, actorId?: string)  => ipcRenderer.invoke('boards:getTasks', boardId, actorId),
    reorder:      (boardIds: string[])                 => ipcRenderer.invoke('boards:reorder', boardIds),
    seedToCloud:  (requestEmail: string)               => ipcRenderer.invoke('boards:seedToCloud', requestEmail),
  },
  analytics: {
    getData:   ()  => ipcRenderer.invoke('analytics:getData'),
    exportPDF: ()  => ipcRenderer.invoke('analytics:exportPDF'),
  },
  trash: {
    list:              ()           => ipcRenderer.invoke('trash:list'),
    count:             ()           => ipcRenderer.invoke('trash:count'),
    restore:           (id: string) => ipcRenderer.invoke('trash:restore', id),
    deletePermanently: (id: string) => ipcRenderer.invoke('trash:deletePermanently', id),
    emptyTrash:        ()           => ipcRenderer.invoke('trash:emptyTrash'),
    restoreAll:        ()           => ipcRenderer.invoke('trash:restoreAll'),
  },
  calendar: {
    list:   (startDate: string, endDate: string) => ipcRenderer.invoke('calendar:list', startDate, endDate),
    get:    (id: string)                         => ipcRenderer.invoke('calendar:get', id),
    create: (data: Record<string, unknown>)      => ipcRenderer.invoke('calendar:create', data),
    update: (id: string, data: Record<string, unknown>) => ipcRenderer.invoke('calendar:update', id, data),
    delete: (id: string)                         => ipcRenderer.invoke('calendar:delete', id),
  },
  files: {
    listAll: () => ipcRenderer.invoke('files:listAll'),
  },
  userGoogle: {
    connect:           (userId: string) => ipcRenderer.invoke('userGoogle:connect', userId),
    getStatus:         (userId: string) => ipcRenderer.invoke('userGoogle:getStatus', userId),
    disconnect:        (userId: string) => ipcRenderer.invoke('userGoogle:disconnect', userId),
    getCalendars:      (userId: string) => ipcRenderer.invoke('userGoogle:getCalendars', userId),
    getCalendarEvents: (userId: string, calendarId: string, startDate: string, endDate: string, calendarColor?: string) => ipcRenderer.invoke('userGoogle:getCalendarEvents', userId, calendarId, startDate, endDate, calendarColor),
    diagnose:          (userId: string) => ipcRenderer.invoke('userGoogle:diagnose', userId),
  },
  todo: {
    getMyTasks:   (userId: string) => ipcRenderer.invoke('todo:getMyTasks', userId),
    complete:     (taskId: string, userId: string, userName: string) => ipcRenderer.invoke('todo:complete', taskId, userId, userName),
    dismiss:      (userId: string, taskId: string) => ipcRenderer.invoke('todo:dismiss', userId, taskId),
    getDismissed: (userId: string) => ipcRenderer.invoke('todo:getDismissed', userId),
    uncomplete:   (taskId: string) => ipcRenderer.invoke('todo:uncomplete', taskId),
  },
  boardMembers: {
    list:        (boardId: string) => ipcRenderer.invoke('boardMembers:list', boardId),
    add:         (boardId: string, userId: string, addedByName: string) => ipcRenderer.invoke('boardMembers:add', boardId, userId, addedByName),
    remove:      (boardId: string, userId: string) => ipcRenderer.invoke('boardMembers:remove', boardId, userId),
    check:       (boardId: string, userId: string) => ipcRenderer.invoke('boardMembers:check', boardId, userId),
    taskCount:   (boardId: string, userId: string) => ipcRenderer.invoke('boardMembers:taskCount', boardId, userId),
    listForUser: (userId: string) => ipcRenderer.invoke('boardMembers:listForUser', userId),
  },
  personalTodo: {
    list:       (userId: string) => ipcRenderer.invoke('personalTodo:list', userId),
    create:     (item: { id: string; user_id: string; title: string; due_date?: string; due_time?: string }) => ipcRenderer.invoke('personalTodo:create', item),
    complete:   (id: string) => ipcRenderer.invoke('personalTodo:complete', id),
    uncomplete: (id: string) => ipcRenderer.invoke('personalTodo:uncomplete', id),
    delete:     (id: string) => ipcRenderer.invoke('personalTodo:delete', id),
  },
  notificationPrefs: {
    get:  (userId: string) => ipcRenderer.invoke('notificationPrefs:get', userId),
    save: (userId: string, prefs: Record<string,unknown>) => ipcRenderer.invoke('notificationPrefs:save', userId, prefs),
  },
  intelligence: {
    getSources:           (params?: Record<string, unknown>) => ipcRenderer.invoke('intelligence:getSources', params),
    analyzeText:          (opts: Record<string, unknown>)    => ipcRenderer.invoke('intelligence:analyzeText', opts),
    fetchUrlMetadata:     (url: string)                      => ipcRenderer.invoke('intelligence:fetchUrlMetadata', url),
    getUnreviewedCount:   ()                                 => ipcRenderer.invoke('intelligence:getUnreviewedCount'),
    updateStatus:         (id: string, status: string, notes?: string, byId?: string, byName?: string) => ipcRenderer.invoke('intelligence:updateStatus', id, status, notes, byId, byName),
    markDuplicate:        (id: string, duplicateOf: string | null) => ipcRenderer.invoke('intelligence:markDuplicate', id, duplicateOf),
    updateConfidence:     (id: string, confidence: string)   => ipcRenderer.invoke('intelligence:updateConfidence', id, confidence),
    updateGeography:      (id: string, geography: string)    => ipcRenderer.invoke('intelligence:updateGeography', id, geography),
    setProject:           (id: string, boardId: string | null) => ipcRenderer.invoke('intelligence:setProject', id, boardId),
    routeToProject:       (sourceId: string, boardId: string) => ipcRenderer.invoke('intelligence:routeToProject', sourceId, boardId),
    updateNotes:          (id: string, notesHtml: string)    => ipcRenderer.invoke('intelligence:updateNotes', id, notesHtml),
    updateContent:        (id: string, content: string)      => ipcRenderer.invoke('intelligence:updateContent', id, content),
    saveAiAnalysis:       (id: string, ai: Record<string, unknown>)         => ipcRenderer.invoke('intelligence:saveAiAnalysis', id, ai),
    saveReconciled:       (id: string, reconciled: Record<string, unknown>) => ipcRenderer.invoke('intelligence:saveReconciled', id, reconciled),
    updateReconciledNotes:(id: string, html: string)         => ipcRenderer.invoke('intelligence:updateReconciledNotes', id, html),
    setHumanRelevance:    (id: string, value: string | null) => ipcRenderer.invoke('intelligence:setHumanRelevance', id, value),
    getKnownTags:         (type: string, boardId: string)              => ipcRenderer.invoke('intelligence:getKnownTags', type, boardId),
    createTag:            (name: string, type: string, boardId: string) => ipcRenderer.invoke('intelligence:createTag', name, type, boardId),
    deleteTag:            (name: string, type: string, boardId: string) => ipcRenderer.invoke('intelligence:deleteTag', name, type, boardId),
    // Realtime invalidate push from main (reuses the workspace:remoteChange pattern).
    onTagsInvalidate:     (cb: (d: { boardId: string | null; scope: 'list' | 'board' }) => void) =>
      ipcRenderer.on('intel:tagsInvalidate', (_e, d) => cb(d)),
    removeTagsInvalidateListeners: () => ipcRenderer.removeAllListeners('intel:tagsInvalidate'),
    // intelligence_sources realtime → re-fetch getSources + the count badges.
    onSourcesInvalidate:  (cb: (d: { boardId: string | null; scope: 'list' | 'board' }) => void) =>
      ipcRenderer.on('intel:sourcesInvalidate', (_e, d) => cb(d)),
    removeSourcesInvalidateListeners: () => ipcRenderer.removeAllListeners('intel:sourcesInvalidate'),
    setArticleTags:       (id: string, type: string, tags: string[]) => ipcRenderer.invoke('intelligence:setArticleTags', id, type, tags),
    logDecision:          (payload: Record<string, unknown>)        => ipcRenderer.invoke('intelligence:logDecision', payload),
    deleteSource:         (id: string)                       => ipcRenderer.invoke('intelligence:deleteSource', id),
    addSocial:            (post: Record<string, unknown>)    => ipcRenderer.invoke('intelligence:addSocial', post),
    addInterview:         (iv: Record<string, unknown>)      => ipcRenderer.invoke('intelligence:addInterview', iv),
    fetchNews:            ()                                 => ipcRenderer.invoke('intelligence:fetchNews'),
    uploadDocument:       (params: Record<string, unknown>)  => ipcRenderer.invoke('intelligence:uploadDocument', params),
    getPipelineStats:     ()                                 => ipcRenderer.invoke('intelligence:getPipelineStats'),
    getStatusCounts:      ()                                 => ipcRenderer.invoke('intelligence:getStatusCounts'),
    getUnscoredCount:     ()                                 => ipcRenderer.invoke('intelligence:getUnscoredCount'),
    rescoreUnscored:      ()                                 => ipcRenderer.invoke('intelligence:rescoreUnscored'),
    importFromContestedSkies: (params: Record<string, unknown>) => ipcRenderer.invoke('intelligence:importFromContestedSkies', params),
    getImportedCount:     ()                                 => ipcRenderer.invoke('intelligence:getImportedCount'),
    confirmImported:      (params: Record<string, unknown>)  => ipcRenderer.invoke('intelligence:confirmImported', params),
  },
  infoPages: {
    list:              ()                                              => ipcRenderer.invoke('infoPages:list'),
    getConfig:         (pageId: string)                               => ipcRenderer.invoke('infoPages:getConfig', pageId),
    saveConfig:        (pageId: string, config: Record<string,unknown>) => ipcRenderer.invoke('infoPages:saveConfig', pageId, config),
    updateMeta:        (pageId: string, meta: Record<string,unknown>) => ipcRenderer.invoke('infoPages:updateMeta', pageId, meta),
    create:            (params: Record<string,unknown>)               => ipcRenderer.invoke('infoPages:create', params),
    delete:            (pageId: string)                               => ipcRenderer.invoke('infoPages:delete', pageId),
    getLastCommit:     (repo: string)                                 => ipcRenderer.invoke('infoPages:getLastCommit', repo),
    getOwners:         (pageId: string)                               => ipcRenderer.invoke('infoPages:getOwners', pageId),
    addOwner:          (pageId: string, userId: string, by: string)   => ipcRenderer.invoke('infoPages:addOwner', pageId, userId, by),
    removeOwner:       (pageId: string, userId: string)               => ipcRenderer.invoke('infoPages:removeOwner', pageId, userId),
    isOwner:           (pageId: string, userId: string)               => ipcRenderer.invoke('infoPages:isOwner', pageId, userId),
    getItems:          (pageId: string, tab?: string)                 => ipcRenderer.invoke('infoPages:getItems', pageId, tab),
    addItem:           (item: Record<string,unknown>)                 => ipcRenderer.invoke('infoPages:addItem', item),
    updateItem:        (id: string, updates: Record<string,unknown>)  => ipcRenderer.invoke('infoPages:updateItem', id, updates),
    deleteItem:        (id: string)                                   => ipcRenderer.invoke('infoPages:deleteItem', id),
    commitItems:       (params: Record<string,unknown>)               => ipcRenderer.invoke('infoPages:commitItems', params),
    getCommits:        (pageId: string, status?: string)              => ipcRenderer.invoke('infoPages:getCommits', pageId, status),
    reviewCommit:      (commitId: string, action: string, params: Record<string,unknown>) => ipcRenderer.invoke('infoPages:reviewCommit', commitId, action, params),
    adminReviewCommit: (commitId: string, action: string, params: Record<string,unknown>) => ipcRenderer.invoke('infoPages:adminReviewCommit', commitId, action, params),
    getPublished:      (pageId: string)                               => ipcRenderer.invoke('infoPages:getPublished', pageId),
    logPublished:      (entry: Record<string,unknown>)                => ipcRenderer.invoke('infoPages:logPublished', entry),
    publishToRepo:     (params: Record<string,unknown>)               => ipcRenderer.invoke('infoPages:publishToRepo', params),
    analyzeWithClaude: (params: Record<string,unknown>)               => ipcRenderer.invoke('infoPages:analyzeWithClaude', params),
    generatePrompt:    (params: Record<string,unknown>)               => ipcRenderer.invoke('infoPages:generatePrompt', params),
    syncSources:          (pageId: string)                            => ipcRenderer.invoke('infoPages:syncSources', pageId),
    getSourceItems:       (pageId: string)                            => ipcRenderer.invoke('infoPages:getSourceItems', pageId),
    sendSourcesToAnalysis:(itemIds: string[])                         => ipcRenderer.invoke('infoPages:sendSourcesToAnalysis', itemIds),
    getSourceStats:       (pageId: string)                            => ipcRenderer.invoke('infoPages:getSourceStats', pageId),
    getAnalysisSources:   (pageId: string)                            => ipcRenderer.invoke('infoPages:getAnalysisSources', pageId),
    getChat:              (pageId: string)                            => ipcRenderer.invoke('infoPages:getChat', pageId),
    clearChat:            (pageId: string)                            => ipcRenderer.invoke('infoPages:clearChat', pageId),
    chat:                 (params: Record<string,unknown>)            => ipcRenderer.invoke('infoPages:chat', params),
    summarizeAnalysis:    (params: Record<string,unknown>)            => ipcRenderer.invoke('infoPages:summarizeAnalysis', params),
    // Source pipeline (two-stage commit lifecycle)
    getSourcePipeline:    (pageId: string)                           => ipcRenderer.invoke('infoPages:getSourcePipeline', pageId),
    sendToReview:         (pageId: string, articleIds: string[])     => ipcRenderer.invoke('infoPages:sendToReview', pageId, articleIds),
    backSourceToNew:      (pageId: string, articleId: string)        => ipcRenderer.invoke('infoPages:backSourceToNew', pageId, articleId),
    moveBackToIntel:      (pageId: string, articleId: string)        => ipcRenderer.invoke('infoPages:moveBackToIntel', pageId, articleId),
    commitSources:        (pageId: string, designNotes: string)      => ipcRenderer.invoke('infoPages:commitSources', pageId, designNotes),
    saveReviewNotes:      (pageId: string, designNotes: string)      => ipcRenderer.invoke('infoPages:saveReviewNotes', pageId, designNotes),
    getSourceChanges:     (pageId: string)                           => ipcRenderer.invoke('infoPages:getSourceChanges', pageId),
    getSourcePipelineCounts: (pageId: string)                        => ipcRenderer.invoke('infoPages:getSourcePipelineCounts', pageId),
  },
  updater: {
    onAvailable:    (cb: (info: { version: string; releaseNotes?: string | null }) => void) =>
      ipcRenderer.on('updater:available', (_e, info) => cb(info)),
    onProgress:     (cb: (p: { percent: number }) => void) =>
      ipcRenderer.on('updater:progress', (_e, p) => cb(p)),
    onReady:        (cb: (info: { version: string }) => void) =>
      ipcRenderer.on('updater:ready', (_e, info) => cb(info)),
    onNotAvailable: (cb: () => void) =>
      ipcRenderer.on('updater:notAvailable', () => cb()),
    onChecking:     (cb: () => void) =>
      ipcRenderer.on('updater:checking', () => cb()),
    onError:        (cb: (err: string) => void) =>
      ipcRenderer.on('updater:error', (_e, err) => cb(err)),
    install:               () => ipcRenderer.invoke('updater:install'),
    openTerminalUpdate:    () => ipcRenderer.invoke('updater:openTerminalUpdate'),
    checkNow:              () => ipcRenderer.invoke('updater:checkNow'),
    downloadNow:    () => ipcRenderer.invoke('updater:downloadNow'),
    getLastChecked: () => ipcRenderer.invoke('updater:getLastChecked'),
    setAutoInstall: (val: boolean) => ipcRenderer.invoke('updater:setAutoInstall', val),
    getAutoInstall: () => ipcRenderer.invoke('updater:getAutoInstall'),
  },
  connection: {
    get:         ()                              => ipcRenderer.invoke('connection:get'),
    onChange:    (cb: (online: boolean) => void) => ipcRenderer.on('connection:changed', (_e, d) => cb(d.online)),
    removeChangeListeners: ()                     => ipcRenderer.removeAllListeners('connection:changed'),
  },
}

if (process.contextIsolated) {
  try {
    contextBridge.exposeInMainWorld('electron', electronAPI)
    contextBridge.exposeInMainWorld('api', api)
  } catch (error) {
    console.error('[Preload] contextBridge error:', error)
  }
} else {
  // @ts-ignore
  window.electron = electronAPI
  // @ts-ignore
  window.api = api
}
